### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by SylisMC** [Juuxel/VanillaParts#22] opened 2020-12-15 00:57 UTC
I think this might be a duplicate of [issue 21](https://github.com/Juuxel/VanillaParts/issues/21)

Crashed with jumploader & fabric API+ 1.16.4

[Multipart crash.txt](https://github.com/Juuxel/VanillaParts/files/5692473/Multipart.crash.txt)

**Comment by AlexIIL** [comment] 2020-12-15 01:41
Yes, this is the same LibNetworkStack crash as #21. A temporary fix is to downgrade fabric api to 0.2.7 (suggested here: https://github.com/Juuxel/VanillaParts/issues/21#issuecomment-743031228) until an LNS update has been released.

**Comment by Juuxel** [comment] 2020-12-15 10:04
Yeah, it's a dupe of #21.

**Closed as completed by Juuxel** 2020-12-15 10:04 UTC
Labels: bug, duplicate
